name: Build dwm

on:
  push:
    branches:
      - h3nc4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends build-essential libxft-dev libxinerama-dev libxkbfile-dev
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build tar
      run: make dist.built
    - name: Gen tag name
      run: echo "SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-8)" >>$GITHUB_ENV
    - name: Create tag
      run: |
        git tag ${{ env.SHORT_SHA }}
        git push origin ${{ env.SHORT_SHA }}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.SHORT_SHA }}
        files: |
          dwm.tgz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
